apiVersion: v1
kind: Service
metadata:
  name: app-service
spec:
  selector:
    app: app
  ports:
    - protocol: TCP
      port: 80           #http://<Node-IP>:80
      targetPort: 3000        # container ke andar ka port
  type: LoadBalancer  # Internet par expose karne ke liye
