apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
        - name: app
          image: devanshlodhi/dev-email:01
          ports:
            - containerPort: 3000
          env:
            - name: DB_NAME
              value: "mongodbb-ser"
            - name: DB_PORT
              value: "27017"
---
apiVersion: v1
kind: Service
metadata:
  name: app-service
spec:
  selector:
    app: app
  ports:
    - protocol: TCP
      port: 80           #http://<Node-IP>:80
      targetPort: 3000        # container ke andar ka port
  type: LoadBalancer  # Internet par expose karne ke liye
