
apiVersion: v1
kind: Service
metadata:
  name: mongodbb-ser
spec:
  selector:
    app: mongodbb
  ports:
  - protocol: TCP
    port: 27017
    targetPort: 27017
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: db-pvc
# spec:
#   accessModes:
#     - ReadWriteOnce
#   resources:
#     requests:
#       storage: 1Gi
# ---
# apiVersion: v1
# kind: Pod
# metadata:
#   name: db-pod
#   labels:
#     app: database
# spec:
#   containers:
#     - name: postgres
#       image: postgres:latest
#       env:
#         - name: POSTGRES_USER
#           value: "user"
#         - name: POSTGRES_PASSWORD
#           value: "password"
#         - name: POSTGRES_DB
#           value: "mydb"
#       ports:
#         - containerPort: 5432
#       volumeMounts:
#         - mountPath: "/var/lib/postgresql/data"
#           name: db-storage
#   volumes:
#     - name: db-storage
#       persistentVolumeClaim:
#         claimName: db-pvc
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: db-service
# spec:
#   selector:
#     app: database
#   ports:
#     - protocol: TCP
#       port: 5432
#       targetPort: 5432
# ---
# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: backend-deployment
# spec:
#   replicas: 2
#   selector:
#     matchLabels:
#       app: backend
#   template:
#     metadata:
#       labels:
#         app: backend
#     spec:
#       containers:
#         - name: backend
#           image: my-backend-image
#           ports:
#             - containerPort: 5000
#           env:
#             - name: DB_HOST
#               value: "db-service"
#             - name: DB_PORT
#               value: "5432"
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: backend-service
# spec:
#   selector:
#     app: backend
#   ports:
#     - protocol: TCP
#       port: 5000
#       targetPort: 5000
#   type: NodePort  # Public access ke liye
