apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-pv
  namespace: my-namespace   # ✅ Namespace Added
spec:
  capacity:
    storage: 2Gi
  volumeMode: Filesystem
  storageClassName: standard
  accessModes:
    - ReadWriteMany # ReadWriteOnce
      #  persistentVolumeReclaimPolicy: Retain # data backake rakhta hai agar PVC delete kr diya to
  hostPath:
    path: "/data/mongo"
    type: DirectoryOrCreate
