apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-pv
  namespace: my-namespace
spec:
  capacity:
    storage: 2Gi
  volumeMode: Filesystem
  storageClassName: standard
  accessModes:
    - ReadWriteOnce  # Changed for hostPath compatibility
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/data/mongo"
    type: DirectoryOrCreate
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-pvc
  namespace: my-namespace
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodbb
  namespace: my-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodbb
  template:
    metadata:
      labels:
        app: mongodbb
    spec:
      containers:
        - name: mongodbb-con
          image: mongo:latest
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: mongo-volume
              mountPath: /data/db
      volumes:
        - name: mongo-volume
          persistentVolumeClaim:
            claimName: mongo-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: mongodbb-ser
  namespace: my-namespace
spec:
  selector:
    app: mongodbb
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
