apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-pvc # Claim name used by the pod to bind to the PV
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce     # kitne pod mai use karne hai
  resources:
    requests:
      storage: 2Gi # Storage request matches the PV capacity
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodbb
spec:
  selector:
    matchLabels:
      app: mongodbb
  replicas: 1 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: mongodbb
    spec:
      containers:
      - name : mongodbb-con
        image : mongo:latest
        ports:
        - containerPort: 27017
        volumeMounts: # Mount the volumes into the container
          - name: mongo-volume
            mountPath: /data/db # Path where MongoDB stores its data
      volumes:
      - name: mongo-volume
        persistentVolumeClaim:
          claimName: mongo-pvc